### ISSUE TITLE
What is this difference between this and store procedure?

### ISSUE THREAD

**Issue by majchuan** [ose-net/yesql.net#111]
I have a question, is this project to support other database rather than store procedure in sql server ?
Comparing to store procedure, what is the advantage?

**Comment by DevD4v3** [comment]
Hello @majchuan,

That's a good question. 
It is true that stored procedures also serve to separate SQL statements (DML) from the application source code, however, there are several disadvantages to this:
- Stored procedure code is not part of version control. If git is used, it will not detect any changes to it.
- Difficult to synchronize changes. Some team member needs to pass a script with stored procedures for developers to synchronize with their local database. The script must then be executed and if it is forgotten, the application will fail.

These disadvantages do not exist in this project, as the SQL files are part of version control and are loaded using YeSQL.NET into the application's memory, so developers do not need to synchronize any changes from db or execute scripts manually.
However, this project does not replace stored procedures. If the SQL query is very complex and requires privileges to be executed, then an SP should be used, and SPs also reduce network traffic.

What I like most about this project is that I can put the SQL files together with the source files (high cohesion) and then all you have to do is load the SQL files from the API provided by YeSQL.NET. See this [example](https://github.com/DentallApp/back-end/tree/dev/src/Core/Reports/UseCases/GetTotalScheduledAppointments) (this is what I mean).

**Comment by Kingside88** [comment]
For MSSQL you can still use DDST Projects where you also separate schema and data logic. 
And Stored Procedures as well. Also it will provide better performance than sending queries threw text

**Comment by DevD4v3** [comment]
Hi @Kingside88, not everyone uses MSSQL. There are also third party tools that allow you to version the database and synchronize changes, such as Redgate Software, however, these tools are usually expensive.

As they say, everything has its trade-offs.
