### ISSUE TITLE
Avoid throwing `AggregateException` when there is only one exception

### ISSUE THREAD

**Issue by Ts-Pytham** [ose-net/yesql.net#61]
The actual code is:
```CSharp
private void CreateAndThrowException()
    {
        var exceptions = new List<Exception>();

        if (_validationResult.HasError())
            exceptions.Add(new YeSqlLoaderException(_validationResult.ErrorMessages));

        if (_parser.ValidationResult.HasError())
            exceptions.Add(new YeSqlParserException(_parser.ValidationResult.ErrorMessages));

        if (exceptions.Count > 0)
            throw new AggregateException(exceptions);
    }

```
This code throws an `AggregateException` regardless if there is only one exception. In this case, it is better to throw **YeSqlParserException** or **YeSqlLoaderException** when there is only one exception.

**Comment by DevD4v3** [comment]
[AggregateException](https://learn.microsoft.com/en-us/dotnet/api/system.aggregateexception?view=net-8.0#definition) type also serves to represent **one or more errors** that occur during the execution of the application.
